/**
 * dsh-notes 客户端样式。
 *
 * 只用官方主题 token(`--dsw-alias-*` / `--dsw-specific-sidebar-fill`),
 * 不写死颜色 —— 明暗主题跟随宿主。
 */
export const CSS = [
  /* 外壳 */
  '.dsh-notes-root{position:relative;display:flex;flex-direction:column;height:100%;min-height:0;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit}',
  '.dsh-notes-header{display:flex;align-items:center;gap:4px;flex:0 0 auto;height:30px;padding:0 8px;border-bottom:1px solid var(--dsw-alias-border-l1);background:var(--dsw-specific-sidebar-fill)}',
  '.dsh-notes-title{font-size:12px;font-weight:600;white-space:nowrap}',
  '.dsh-notes-sub{font-size:11px;color:var(--dsw-alias-label-secondary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dsh-notes-spacer{flex:1 1 auto}',
  // 按钮:无描边,hover 才浮一层底色(与 DSH 自身控件同款观感)
  '.dsh-notes-btn{appearance:none;border:1px solid transparent;background:transparent;color:var(--dsw-alias-label-secondary);border-radius:6px;padding:2px 6px;font:inherit;font-size:13px;line-height:1.5;cursor:pointer;white-space:nowrap;transition:background .12s ease,color .12s ease,opacity .12s ease}',
  '.dsh-notes-btn:hover:not([disabled]){color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-btn:active:not([disabled]){background:var(--dsw-alias-bg-layer-3,var(--dsw-alias-bg-layer-2))}',
  '.dsh-notes-btn[disabled]{opacity:.4;cursor:default}',
  // 分段按钮组(工具栏用):首尾圆角 + 组内 hairline,比"每个按钮各自带框"干净
  '.dsh-notes-seg{display:inline-flex;align-items:center;gap:0;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;padding:1px;background:color-mix(in srgb, var(--dsw-alias-bg-layer-1) 55%, transparent)}',
  '.dsh-notes-seg>.dsh-notes-btn{border-radius:6px}',
  '.dsh-notes-seg>.dsh-notes-btn+.dsh-notes-btn{margin-left:1px}',
  '.dsh-notes-body{display:flex;flex:1 1 auto;min-height:0}',

  /* 树列 */
  '.dsh-notes-tree{flex:0 0 auto;min-width:0;display:flex;flex-direction:column;overflow:hidden;background:var(--dsw-specific-sidebar-fill);border-right:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-tree-inner{display:flex;flex-direction:column;min-height:0;flex:1 1 auto}',
  '.dsh-notes-tree-head{display:flex;align-items:center;gap:4px;flex:0 0 auto;min-height:30px;padding:0 6px 0 8px;font-size:12px;color:var(--dsw-alias-label-secondary);border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-tree-title{font-weight:600;color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-tree-body{flex:1 1 auto;min-height:0;overflow:auto;padding:3px 0}',
  '.dsh-notes-row{display:flex;align-items:center;gap:4px;height:26px;padding-right:6px;font-size:13px;cursor:pointer;white-space:nowrap;user-select:none}',
  '.dsh-notes-row:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-row-selected{background:var(--dsw-alias-bg-layer-2);box-shadow:inset 2px 0 0 var(--dsw-alias-brand-primary)}',
  '.dsh-notes-row-ref .dsh-notes-row-label{color:var(--dsw-alias-label-secondary)}',
  /* 分类 vs 笔记:一眼可分 —— 分类加粗带文件夹;笔记常规字重、次要色 */
  '.dsh-notes-row-collection .dsh-notes-row-label{font-weight:600;color:var(--dsw-alias-label-primary)}',
  '.dsh-notes-row-note .dsh-notes-row-label,.dsh-notes-row-unfiled .dsh-notes-row-label{color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-row-note.dsh-notes-row-selected .dsh-notes-row-label{color:var(--dsw-alias-label-primary)}',
  '.dsh-notes-row-drop{background:var(--dsw-alias-bg-layer-2);box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary)}',
  /* 拖放指示:插入线(上/下)/ 容器高亮(内部)/ 拖动源淡出 / 跟随光标的层级标签 */
  '.dsh-notes-row-ins-before{box-shadow:inset 0 2px 0 0 var(--dsw-alias-brand-primary)}',
  '.dsh-notes-row-ins-after{box-shadow:inset 0 -2px 0 0 var(--dsw-alias-brand-primary)}',
  '.dsh-notes-row-ins-inside{background:var(--dsw-alias-bg-layer-2);box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary);border-radius:5px}',
  '.dsh-notes-row-dragging{opacity:.45}',
  '.dsh-notes-drop-chip{position:fixed;z-index:40;pointer-events:none;max-width:340px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:2px 9px;border-radius:999px;font-size:11px;line-height:1.7;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-label-primary);border:1px solid var(--dsw-alias-border-l2);box-shadow:0 6px 18px rgba(0,0,0,.2)}',
  '.dsh-notes-tree-body-dragging{background:color-mix(in srgb, var(--dsw-alias-brand-primary) 4%, transparent)}',
  /* 拖动中把所有"可以放进去"的容器标出来,不然只有悬停到才知道哪儿能放 */
  '.dsh-notes-tree-body-dragging .dsh-notes-row-collection{box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l2);border-radius:5px}',
  '.dsh-notes-drop-line{height:2px;margin:3px 8px;border-radius:2px;background:var(--dsw-alias-brand-primary)}',
  '.dsh-notes-drop-root{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary)}',
  '.dsh-notes-glyph{flex:0 0 auto;font-size:11px;line-height:1;opacity:.9}',
  '.dsh-notes-caret{flex:0 0 auto;width:12px;font-size:11px;color:var(--dsw-alias-label-secondary);text-align:center}',
  '.dsh-notes-row-label{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis}',
  '.dsh-notes-count{flex:0 0 auto;font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-badge{flex:0 0 auto;max-width:120px;overflow:hidden;text-overflow:ellipsis;font-size:11px;padding:0 5px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-hint{padding:7px 10px;font-size:12px;line-height:1.6;color:var(--dsw-alias-label-secondary);border-top:1px solid var(--dsw-alias-border-l1)}',

  /* 输入条 / 状态 */
  '.dsh-notes-compose{display:flex;align-items:center;gap:4px;padding:4px 6px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-input{flex:1 1 auto;min-width:0;box-sizing:border-box;padding:3px 7px;border-radius:5px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px}',
  '.dsh-notes-input:focus{outline:none;border-color:var(--dsw-alias-brand-primary)}',
  /* 状态提示:浮层 toast —— 之前它插在正常流里,出现/消失会把下面的内容整体顶一下(用户看到"一闪一闪") */
  '.dsh-notes-status{position:absolute;top:34px;left:50%;transform:translateX(-50%);z-index:50;pointer-events:none;max-width:80%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:3px 10px;border-radius:999px;font-size:11px;color:var(--dsw-alias-state-success-primary);background:var(--dsw-alias-bg-overlay);border:1px solid var(--dsw-alias-border-l2);box-shadow:0 6px 18px rgba(0,0,0,.18);animation:dsh-notes-status-fade 2.4s forwards}',
  '@keyframes dsh-notes-status-fade{0%,70%{opacity:1}100%{opacity:0}}',
  '.dsh-notes-error{display:flex;align-items:flex-start;gap:6px;padding:4px 6px 4px 10px;font-size:11px;line-height:1.6;color:var(--dsw-alias-state-error-primary);white-space:pre-wrap}',
  '.dsh-notes-error-text{flex:1 1 auto;min-width:0}',
  '.dsh-notes-error-close{flex:0 0 auto;appearance:none;border:none;background:transparent;color:inherit;font:inherit;font-size:13px;line-height:1;padding:0 4px;cursor:pointer;opacity:.7}',
  '.dsh-notes-error-close:hover{opacity:1}',
  /* 右键菜单 */
  '.dsh-notes-menu{position:fixed;z-index:60;min-width:172px;padding:4px;border-radius:8px;background:var(--dsw-alias-bg-overlay);border:1px solid var(--dsw-alias-border-l2);box-shadow:0 10px 28px rgba(0,0,0,.22);display:flex;flex-direction:column;gap:1px}',
  '.dsh-notes-menu-item{appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;line-height:1.6;text-align:left;padding:4px 9px;border-radius:5px;cursor:pointer;white-space:nowrap}',
  '.dsh-notes-menu-item:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-menu-sep{height:1px;margin:3px 4px;background:var(--dsw-alias-border-l1)}',

  /* 左列标签页(文件 / 大纲)+ 大纲 */
  '.dsh-notes-column{display:flex;flex-direction:column;flex:1 1 auto;min-height:0;min-width:0}',
  '.dsh-notes-panel-tabs{display:flex;align-items:center;gap:2px;flex:0 0 auto;padding:4px 6px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-tab{appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:12px;line-height:1.6;padding:2px 9px;border-radius:5px;cursor:pointer}',
  '.dsh-notes-panel-tab:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}',
  '.dsh-notes-panel-tab-on{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-weight:600}',
  '.dsh-notes-outline{flex:1 1 auto;min-height:0;overflow:auto;padding:4px 0}',
  '.dsh-notes-outline-row{display:flex;align-items:center;gap:6px;height:24px;padding-right:8px;font-size:12.5px;color:var(--dsw-alias-label-secondary);cursor:pointer;white-space:nowrap;user-select:none}',
  '.dsh-notes-outline-row:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}',
  '.dsh-notes-outline-active{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);box-shadow:inset 2px 0 0 var(--dsw-alias-brand-primary)}',
  '.dsh-notes-outline-text{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis}',
  '.dsh-notes-outline-h{flex:0 0 auto;font-size:9.5px;letter-spacing:.02em;color:var(--dsw-alias-label-secondary);opacity:.7}',
  '.dsh-notes-outline-h1{color:var(--dsw-alias-brand-primary);opacity:1}',
  '.dsh-notes-outline-h2{opacity:.92}',
  '.dsh-notes-outline-h3{opacity:.8}',

  /* 分隔条 / 收起条 */
  '.dsh-notes-resizer{flex:0 0 auto;width:4px;cursor:col-resize;background:transparent}',
  '.dsh-notes-resizer:hover{background:var(--dsw-alias-border-l2)}',
  '.dsh-notes-rail{flex:0 0 auto;display:flex;flex-direction:column;align-items:center;gap:4px;width:30px;padding:4px 0;border-right:1px solid var(--dsw-alias-border-l1);background:var(--dsw-specific-sidebar-fill)}',
  '.dsh-notes-rail .dsh-notes-btn{min-width:24px;padding:3px 0;font-size:17px;line-height:1;text-align:center}',
  '.dsh-notes-toolbar{display:flex;align-items:center;gap:2px;flex:0 0 auto}',
  '.dsh-notes-toolbar .dsh-notes-btn{min-width:24px;padding:2px 0;font-size:16px;line-height:1.2;text-align:center}',

  /* 分栏 + 标签栏(P6) */
  '.dsh-notes-area{flex:1 1 auto;min-width:0;min-height:0;display:flex}',
  '.dsh-notes-pane{flex:1 1 0;min-width:0;min-height:0;display:flex;flex-direction:column;overflow:hidden}',
  '.dsh-notes-area-split .dsh-notes-pane+.dsh-notes-pane{border-left:1px solid var(--dsw-alias-border-l2)}',
  '.dsh-notes-pane-body{flex:1 1 auto;min-height:0;display:flex;flex-direction:column;overflow:hidden}',
  '.dsh-notes-tabpage{flex:1 1 auto;min-height:0;flex-direction:column}',
  '.dsh-notes-tabstrip{flex:0 0 auto;display:flex;align-items:center;gap:2px;padding:2px 4px;overflow-x:auto;overflow-y:hidden;border-bottom:1px solid var(--dsw-alias-border-l1);background:var(--dsw-specific-sidebar-fill);scrollbar-width:thin}',
  '.dsh-notes-tabstrip-on{background:var(--dsw-alias-bg-layer-1)}',
  '.dsh-notes-tabstrip .dsh-notes-btn{flex:0 0 auto;min-width:20px;padding:1px 4px;font-size:12px}',
  '.dsh-notes-tab{flex:0 0 auto;display:flex;align-items:center;gap:3px;max-width:150px;padding:1px 4px 1px 7px;border:1px solid transparent;border-radius:5px;font-size:11.5px;color:var(--dsw-alias-label-secondary);cursor:pointer;user-select:none}',
  '.dsh-notes-tab:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}',
  '.dsh-notes-tab-on{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-border-l1);color:var(--dsw-alias-label-primary);font-weight:600}',
  '.dsh-notes-tab-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-tab-badge{font-size:10px;opacity:.7}',
  '.dsh-notes-tab-close{appearance:none;border:none;background:transparent;color:inherit;font:inherit;font-size:12px;line-height:1;padding:0 2px;border-radius:3px;cursor:pointer;opacity:.55}',
  '.dsh-notes-tab-close:hover{opacity:1;background:var(--dsw-alias-bg-layer-1)}',
  /* 纳入管理面板(候选/杂项) */
  '.dsh-notes-missing{flex:0 0 auto;display:flex;flex-direction:column;gap:6px;margin:6px;padding:9px 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-alias-bg-layer-1)}',
  '.dsh-notes-missing-title{font-size:12.5px;font-weight:600}',
  '.dsh-notes-missing-actions{display:flex;align-items:center;gap:4px;flex-wrap:wrap}',
  '.dsh-notes-missing .dsh-notes-input{font-size:11px}',
  '.dsh-notes-ws{appearance:none;border:none;background:transparent;color:inherit;font:inherit;font-size:11px;padding:0 2px;margin-right:4px;cursor:pointer;border-radius:4px;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-ws:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-wsmenu{position:absolute;z-index:60;top:29px;left:8px;min-width:260px;max-height:60%;overflow:auto;display:flex;flex-direction:column;padding:4px 0;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-overlay);box-shadow:0 12px 30px rgba(0,0,0,.28)}',
  '.dsh-notes-wsmenu-item{display:flex;align-items:center;gap:8px;width:100%;appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;text-align:left;padding:5px 10px;cursor:pointer}',
  '.dsh-notes-wsmenu-item:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-wsmenu-on{font-weight:600}',
  '.dsh-notes-wsmenu-name{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-wsmenu-add{padding:4px 8px;border-top:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-overlay{position:absolute;inset:0;z-index:70;display:flex;align-items:flex-start;justify-content:center;padding-top:34px;background:color-mix(in srgb, var(--dsw-alias-bg-base) 55%, transparent)}',
  '.dsh-notes-panel{width:96%;max-width:760px;height:80%;display:flex;flex-direction:column;border-radius:12px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-overlay);box-shadow:0 8px 24px rgba(0,0,0,.18);overflow:hidden}',
  '.dsh-notes-panel-sm{max-width:520px;height:auto;max-height:72%;margin-top:34px}',
  '.dsh-notes-panel-note{flex:0 0 auto;padding:6px 10px;font-size:11px;line-height:1.6;color:var(--dsw-alias-label-secondary);border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-pad{padding:10px}',
  '.dsh-notes-panel-head{flex:0 0 auto;display:flex;align-items:center;gap:8px;padding:7px 10px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-title{font-size:13px;font-weight:600;white-space:nowrap}',
  '.dsh-notes-panel-stats{font-size:11px;color:var(--dsw-alias-label-secondary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dsh-notes-panel-bar{flex:0 0 auto;display:flex;align-items:center;gap:8px;padding:6px 10px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-search{flex:1 1 auto}',
  '.dsh-notes-panel-segments{flex:0 0 auto;display:flex;align-items:center;gap:2px}',
  '.dsh-notes-panel-scope{flex:0 0 auto;display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:4px 10px;font-size:11px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-scope-chip{display:inline-flex;align-items:center;gap:2px;padding:1px 3px 1px 7px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;font-size:11px}',
  '.dsh-notes-scope-chip .dsh-notes-btn{font-size:11px;padding:0 3px;line-height:1.3}',
  '.dsh-notes-scope-input{flex:0 1 130px;min-width:90px;font-size:11px;padding:2px 6px}',
  '.dsh-notes-panel-crumb{flex:0 0 auto;display:flex;align-items:center;gap:6px;padding:4px 10px;font-size:11px;color:var(--dsw-alias-label-secondary);border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-panel-error{flex:0 0 auto;display:flex;align-items:center;gap:6px;padding:5px 10px;font-size:12px;color:var(--dsw-alias-state-error-primary);background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent)}',
  '.dsh-notes-panel-body{flex:1 1 auto;min-height:0;overflow:auto;padding:4px 0}',
  '.dsh-notes-panel-row{display:flex;align-items:center;gap:8px;padding:3px 10px;border-radius:6px;transition:background .12s ease}',
  '.dsh-notes-panel-row:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-panel-name{flex:1 1 auto;min-width:0;display:flex;align-items:baseline;gap:8px;appearance:none;border:none;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer;overflow:hidden}',
  '.dsh-notes-panel-title2{font-size:12.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:45%}',
  '.dsh-notes-panel-name .dsh-notes-mono{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1 1 auto;min-width:0}',
  '.dsh-notes-panel-group{margin:2px 0 6px}',
  '.dsh-notes-panel-grouph{width:100%;display:flex;align-items:center;gap:8px;appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;font-weight:600;text-align:left;padding:4px 10px;border-radius:6px;cursor:pointer}',
  '.dsh-notes-panel-grouph:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-panel-grouplist{padding-left:10px}',
  '.dsh-notes-panel-more{appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:11px;padding:2px 10px;cursor:pointer}',
  '.dsh-notes-panel-globs{margin-top:8px;border-top:1px solid var(--dsw-alias-border-l1);padding-top:6px}',
  '.dsh-notes-panel-rule{display:flex;align-items:center;gap:8px;padding:3px 10px;font-size:12px}',
  '.dsh-notes-panel-rule .dsh-notes-mono{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-trash-list{flex:1 1 auto;min-height:0;overflow:auto;padding:6px 8px}',
  '.dsh-notes-trash-row{display:flex;align-items:center;gap:8px;padding:5px 8px;border-radius:6px;transition:background .12s ease}',
  '.dsh-notes-trash-row:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-trash-name{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12.5px}',
  '.dsh-notes-trash-meta{flex:0 0 auto;font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-trash-danger{color:var(--dsw-alias-state-error-primary)}',
  '.dsh-notes-panel-foot{flex:0 0 auto;display:flex;align-items:center;gap:8px;padding:6px 10px;border-top:1px solid var(--dsw-alias-border-l1);font-size:11px}',
  '.dsh-notes-panel-foot .dsh-notes-dim{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',

  /* 编辑区 */
  '.dsh-notes-editor{flex:1 1 auto;min-width:0;display:flex;flex-direction:column;overflow:auto}',
  '.dsh-notes-editor-pane{display:flex;flex-direction:column;height:100%;min-height:0;flex:1 1 auto}',
  '.dsh-notes-editor-bar{position:relative;display:flex;align-items:center;gap:4px;flex:0 0 auto;min-height:32px;padding:2px 8px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-editor-name{font-size:13px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:45%}',
  /* 工具栏是**一行**命令:窄侧栏(约 700px)放不下时横向滚动,绝不换行把编辑区顶下去 */
  '.dsh-notes-editor-tools{flex:0 1 auto;min-width:0;overflow-x:auto;overflow-y:hidden;flex-wrap:nowrap;scrollbar-width:thin}',
  '.dsh-notes-editor-tools::-webkit-scrollbar{height:6px}',
  '.dsh-notes-editor-tools::-webkit-scrollbar-thumb{background:var(--dsw-alias-border-l2);border-radius:3px}',
  '.dsh-notes-editor-tools .dsh-notes-btn{min-width:24px;min-height:24px;padding:2px 4px;display:inline-flex;align-items:center;justify-content:center;gap:1px}',
  /* 分组之间的细分隔线(不参与收缩,免得被挤没) */
  '.dsh-notes-sep{flex:0 0 auto;align-self:center;width:1px;height:15px;margin:0 4px;background:var(--dsw-alias-border-l1);opacity:.75}',
  '.dsh-notes-h-mark{font-size:12px;font-weight:700;line-height:1}',
  '.dsh-notes-caret-mark{font-size:8px;line-height:1;opacity:.75}',
  /* 弹出面板:挂在编辑器条上(不是工具栏里)—— 工具栏是 overflow:auto,放里面会被裁掉 */
  '.dsh-notes-popover{position:absolute;top:100%;z-index:80;display:flex;flex-direction:column;gap:2px;padding:4px;min-width:112px;max-width:min(280px,92%);border-radius:8px;background:var(--dsw-alias-bg-overlay);border:1px solid var(--dsw-alias-border-l2);box-shadow:0 10px 28px rgba(0,0,0,.22)}',
  '.dsh-notes-popover-item{appearance:none;border:none;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;line-height:1.6;text-align:left;padding:4px 9px;border-radius:5px;cursor:pointer;white-space:nowrap}',
  '.dsh-notes-popover-item:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsh-notes-popover-form{gap:5px;padding:6px;min-width:236px}',
  '.dsh-notes-popover-input{width:100%;box-sizing:border-box}',
  '.dsh-notes-popover-row{display:flex;align-items:center;gap:4px}',
  '.dsh-notes-popover-label{font-size:11px;line-height:1.6;color:var(--dsw-alias-label-secondary);white-space:nowrap;padding:0 2px}',
  /* 表格选择网格:悬停高亮已选的行×列 */
  '.dsh-notes-grid{display:flex;flex-direction:column;gap:2px;padding:2px}',
  '.dsh-notes-grid-row{display:flex;gap:2px}',
  '.dsh-notes-grid-cell{appearance:none;width:14px;height:14px;padding:0;border:1px solid var(--dsw-alias-border-l2);border-radius:2px;background:var(--dsw-alias-bg-layer-1);cursor:pointer}',
  '.dsh-notes-grid-cell-on{background:color-mix(in srgb, var(--dsw-alias-brand-primary) 22%, transparent);border-color:var(--dsw-alias-brand-primary)}',
  '.dsh-notes-editor-host{flex:1 1 auto;min-height:0;overflow:hidden;display:flex}',
  '.dsh-notes-editor-host .cm-editor{flex:1 1 auto;min-width:0}',
  '.dsh-notes-editor-status{display:flex;align-items:center;gap:8px;flex:0 0 auto;padding:3px 10px;font-size:11px;color:var(--dsw-alias-label-secondary);border-top:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-crash{flex:1 1 auto;min-height:0;overflow:auto;margin:0;padding:10px;font-family:var(--dsw-font-mono,ui-monospace,monospace);font-size:11px;line-height:1.5;white-space:pre-wrap;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1)}',
  '.dsh-notes-notice{flex:0 0 auto;padding:4px 10px;font-size:12px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-conflict{display:flex;align-items:center;gap:8px;flex:0 0 auto;padding:5px 10px;font-size:12px;color:var(--dsw-alias-state-error-primary);background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent);border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.dsh-notes-conflict-text{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-notes-empty{display:flex;align-items:center;justify-content:center;flex:1 1 auto;padding:16px;text-align:center;font-size:13px;line-height:1.7;color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-placeholder{display:flex;flex-direction:column;gap:6px;padding:14px 16px}',
  '.dsh-notes-placeholder-title{font-size:15px;font-weight:600}',
  '.dsh-notes-dim{font-size:11px;line-height:1.6;color:var(--dsw-alias-label-secondary)}',
  '.dsh-notes-mono{font-family:var(--dsw-font-mono,ui-monospace,SFMono-Regular,Menlo,monospace);word-break:break-all}',
].join('\n')
